### ISSUE TITLE
But how does it work though ?

### ISSUE THREAD

**Issue by v-fox** [Brokemia/TrainerReborn#2]
So, I've installed Courier into GOG version of the game, ran MiniInstaller.exe with mono under Linux and put TrainerReborn-1.0.2.zip into Mods, it spew Mods/Cache/TrainerReborn.dll after launching the game with wine and there is new menu about custom levels but that's it. But there doesn't seem to be any menus or hotkeys for anything else. Is something supposed to happen ?

**Comment by Brokemia** [comment]
There should be a Third-Party Mod Options Menu under the normal Options menu. If that doesn't have the trainer options in it, please send the log.txt file from your main game folder.

**Comment by v-fox** [comment]
> There should be a Third-Party Mod Options Menu under the normal Options menu. If that doesn't have the trainer options in it, please send the log.txt file from your main game folder.

There is the menu but it only has 2 options about "saving/loading json" that don't do anything.
Here's the file: [log.txt](https://github.com/Brokemia/TrainerReborn/files/8094210/log.txt)

**Comment by Brokemia** [comment]
What version of Courier do you have? I think I see the issue but I want to confirm

**Comment by Brokemia** [comment]
Yep, just found it, I made a version 1.0.3 then uploaded it only on Discord and forgot to put it here. I'll do that now

**Comment by Brokemia** [comment]
That version is on the releases page now, let me know if it works

**Comment by v-fox** [comment]
> What version of Courier do you have? I think I see the issue but I want to confirm

Just the latest there is: 0.7

> Yep, just found it, I made a version 1.0.3 then uploaded it only on Discord and forgot to put it here. I'll do that now
> That version is on the releases page now, let me know if it works

Thanks, works like a charm now ! Great addition for avoiding some not-so-great game-design decisions.
